# Generated by Django 3.2.23 on 2024-01-31 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerImages',
        ),
    ]
