# Generated by Django 3.2.23 on 2024-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20240117_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
