# Generated by Django 3.2.23 on 2023-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20231210_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='paid_until',
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
    ]
