# Generated by Django 3.2.23 on 2024-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('line_1', 'line_2', 'city', 'postcode')},
        ),
    ]
