# Generated by Django 3.2.23 on 2024-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboarding_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(choices=[('basic', 'Basic'), ('enterprise', 'Enterprise'), ('premium', 'Premium')], max_length=255),
        ),
    ]
