# Generated by Django 3.2.23 on 2023-12-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plan', to='onboarding.plan'),
        ),
    ]
