# Generated by Django 3.2.23 on 2023-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_onboarding_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='stripe_connect_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
