# Generated by Django 3.2.23 on 2023-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('shipped', 'Shippped'), ('delivered', 'Delivered')], default='packed', max_length=30),
        ),
    ]
