# Generated by Django 3.2.23 on 2024-01-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
