name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USER_NAME }}

          script: |
            cd /home/ubuntu/SAAS-Ecommerce
            eval "$(ssh-agent -s)"
            ssh-add /home/ubuntu/.ssh/id_rsa
            git pull
            source venv/bin/activate
            source .env
            sudo systemctl restart gunicorn
          
