name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Key
        run: |
          echo "${{secrets.SSH_HOST}}" > ssh_key_debug
          cat ssh_key_debug
        shell: bash
