name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
            coverage run manage.py test
            coverage xml -o coverage.xml
            coverage html -d htmlcov

      - name: Check coverage
        run: |
          python check_coverage.py
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USER_NAME }}

          script: |
            cd /home/ubuntu/SAAS-Ecommerce
            eval "$(ssh-agent -s)"
            ssh-add /home/ubuntu/.ssh/id_rsa
            git pull
            source venv/bin/activate
            source .env
            sudo systemctl restart gunicorn
          
