name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 68.183.32.93
          key: ${{secrets.SSH_KEY}}
          username: root

          script: |
            cd /home/sagheer/SAAS-Ecommerce
            git pull
            /home/sagheer/SAAS-Ecommerce
            systemctl restart gunicorn
            echo 'Deployment successful to digital ocean'