name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /home/sagheer/SAAS-Ecommerce
            echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            git config --global --add safe.directory /home/sagheer/SAAS-Ecommerce
            git pull origin master
            systemctl restart gunicorn
            echo 'Deployment successful to digital ocean'