name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /home/sagheer/SAAS-Ecommerce
            eval "$(ssh-agent -s)"
            ssh-add /home/sagheer/.ssh/id_rsa
            git pull
          
