name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          HOSTNAME: ${{secrets.SSH_HOST}}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_NAME: ${{secrets.USER_NAME}}

          script: |
            cd /home/ubuntu/SAAS-Ecommerce
            eval "$(ssh-agent -s)"
            ssh-add /home/ubuntu/.ssh/id_rsa
            git pull
            source venv/bin/activate
            source .env
            python manage.py collectstatic --no-input
            sudo systemctl restart gunicorn
          
