# Generated by Django 3.2.23 on 2023-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231225_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='public_schema_product_id',
            field=models.IntegerField(db_index=True, default=False),
        ),
    ]
