# Generated by Django 3.2.23 on 2024-01-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240107_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_cover_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock available'),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
